### ISSUE TITLE
replace_all instead of replace?

### ISSUE THREAD

**Issue by raspofabs** [RealAtix/mdbook-private#1]
https://github.com/RealAtix/mdbook-private/blob/b62db6e8a703225d3d53cbb82fd1b46501d2055f/src/lib.rs#L64C27-L64C27

I think this is why my multiple private sections are not showing up, but instead seem to be removed as per normal comments.

**Comment by RealAtix** [comment]
Good catch, merged and bumped to v0.1.1. Thanks!
