### ISSUE TITLE
Nonumbered Chapters are Numbered if remove=true

### ISSUE THREAD

**Issue by sepbijani** [RealAtix/mdbook-private#12]
Hi, the behavior is not consistent.
When "remove=false" in book.toml, the output will be:
![image](https://github.com/RealAtix/mdbook-private/assets/160477972/8c2abe33-c15f-40e7-b008-59a5ea9c9969)
however for remove=true, the non_numbered chapter (prefix chapter) will be numbered:
![image](https://github.com/RealAtix/mdbook-private/assets/160477972/2e90eac5-4a4c-479d-a512-d4d98eff88b5)
The SUMMARY.md file is as:
``` Markdown
# Summary
[Nonumber Chapter](./no_number.md)
# Content
- [Chapter 1](./chapter_1.md)
  - [Sub chapter](./_chapter_1_sub.md)
- [Chapter 2](./_chapter_2.md)
  - [Sub chapter](./chapter_2_sub.md)
```

**Comment by RealAtix** [comment]
Hi, it seems I did not take into account prefix chapters, I'll look into it.

**Comment by RealAtix** [comment]
I'll include this in the next release, until then you can run it by cloning the repo's master branch and running `cargo build --release && cargo install --path .` to install the latest locally.

**Comment by sepbijani** [comment]
Thanks for the bug fix!
