### ISSUE TITLE
Numbering issue with private pages 

### ISSUE THREAD

**Issue by jmorel** [RealAtix/mdbook-private#6]
When `remove=true`, private pages are still taken into account when generating section numbers in the table of contents.

For example with this `summary.md`:

```md
# Summary

- [Chapter 1](./chapter_1.md)
  - [Sub chapter](./_chapter_1_sub.md)
- [Chapter 2](./_chapter_2.md)
  - [Sub chapter](./chapter_2_sub.md)
- [If remove=false, should be numbered 3 else should be 2](./chapter_3.md)
```

If `remove=true`:

![Capture d’écran 2023-10-06 à 09 32 40](https://github.com/RealAtix/mdbook-private/assets/1270900/609b61d9-5fed-40a1-a3e9-26dbd06c285b)

if `remove=false`:

![Capture d’écran 2023-10-06 à 09 33 25](https://github.com/RealAtix/mdbook-private/assets/1270900/25262f56-2f6a-4e42-aa3e-eb6e8426614b)

I'm guessing the issue also occurs with sub sections.

**Comment by RealAtix** [comment]
Hi, thanks for reporting. I will look into it.

It will indeed also occur in subsections.

**Comment by RealAtix** [comment]
Please check #7
