### ISSUE TITLE
Can't remove table rows

### ISSUE THREAD

**Issue by valeriyk** [RealAtix/mdbook-private#8]
I have a usecase where I would like to hide certain rows in a table. However currently there's no way to do this due to vanishing newline chars:

This works when I keep, but doesn't work when I remove:
```
Col1 | Col2
---|---
<!--private
Row0.Col0 | Row0.Col1
-->
Row1.Col0 | Row1.Col1
```

And this works when I remove, but doesn't work when I keep:
```
Col1 | Col2
---|---
<!--private
Row0.Col0 | Row0.Col1
-->Row1.Col0 | Row1.Col1
```

The easiest and most straightforward way would be to change the regexp to
```
Regex::new(r"<!--\s*private\b\s*[\r?\n]?((?s).*?)[\r?\n]?\s*-->[\r?\n]?").unwrap();
```
But this breaks existing tests.
Alternative solution would be to run the replace_all twice with a different regexp, which is not ideal either.

**Comment by RealAtix** [comment]
Hi, thank you for looking into it. 
I ended up using your regex suggestion to catch the newline at the closing of the private tag. I added the newline back if a private section is kept. Fixed the tests as the newline that previously remained was unnecessary.

Please check #9 and let me know!
